# Site settings
title: Caitlin Meyer
description: "My MicroMasters Portfolio"
url: ""

author:
  name: "Caitlin Meyer"
  email: "caitlin.meyer@yale.edu"
  url: ""

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables


# Options
custom_header: false
custom_nav_footer: false
reverse: false
